version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
      # - image: circleci/mysql:5.7-ram
      # - image: redis:3
    working_directory: ~/repo
    steps:
      - checkout
      # - run: sudo apt update
      # lolipopに秘密鍵で入れるように
      - run: scp -oStrictHostKeyChecking=no -P ${DEPLOY_PORT} ~/repo/* ${DEPLOY_USER}@${DEPLOY_SERVER}:~/web/futurepop

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
        filters:
          branches:
            only:
              - master