version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
      # - image: circleci/mysql:5.7-ram
      # - image: redis:3
    steps:
      - checkout
      # - run: sudo apt update

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build